INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (1, 'TCGA-DU-8164', 'Oligodendroglioma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (2, 'TCGA-QH-A6CY', 'Mixed glioma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (3, 'TCGA-HW-A5KM', 'Astrocytoma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (4, 'TCGA-HT-8010', 'Oligodendroglioma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (5, 'TCGA-E1-A7YE', 'Astrocytoma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (6, 'TCGA-S9-A6WG', 'Astrocytoma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (7, 'TCGA-DB-A4X9', 'Mixed glioma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (8, 'TCGA-P5-A72U', 'Oligodendroglioma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (9, 'TCGA-P5-A5F4', 'Oligodendroglioma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (10, 'TCGA-FG-A4MY', 'Mixed glioma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (11, 'TCGA-HT-8018', 'Mixed glioma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (12, 'TCGA-HT-A5R5', 'Oligodendroglioma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (13, 'TCGA-DU-A76K', 'Oligodendroglioma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (14, 'TCGA-QH-A6CV', 'Mixed glioma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (15, 'TCGA-FG-A70Y', 'Oligodendroglioma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (16, 'TCGA-FG-5962', 'Oligodendroglioma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (17, 'TCGA-DU-6402', 'Astrocytoma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (18, 'TCGA-F6-A8O3', 'Oligodendroglioma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (19, 'TCGA-DB-A75M', 'Astrocytoma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (20, 'TCGA-QH-A65Z', 'Oligodendroglioma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (21, 'TCGA-DB-A4XG', 'Oligodendroglioma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (22, 'TCGA-DU-5851', 'Mixed glioma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (23, 'TCGA-DB-A4XH', 'Mixed glioma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (24, 'TCGA-HT-7874', 'Oligodendroglioma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (25, 'TCGA-DH-A66D', 'Astrocytoma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (26, 'TCGA-DU-5871', 'Mixed glioma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (27, 'TCGA-FG-A60J', 'Mixed glioma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (28, 'TCGA-E1-A7Z3', 'Astrocytoma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (29, 'TCGA-DU-7011', 'Mixed glioma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (30, 'TCGA-06-0122', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (31, 'TCGA-VW-A8FI', 'Astrocytoma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (32, 'TCGA-DU-A7TB', 'Oligodendroglioma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (33, 'TCGA-12-3651', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (34, 'TCGA-19-0957', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (35, 'TCGA-HW-8320', 'Astrocytoma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (36, 'TCGA-DU-6542', 'Mixed glioma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (37, 'TCGA-E1-A7YN', 'Astrocytoma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (38, 'TCGA-DU-6397', 'Oligodendroglioma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (39, 'TCGA-CS-5394', 'Astrocytoma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (40, 'TCGA-FG-A4MX', 'Astrocytoma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (41, 'TCGA-S9-A6TS', 'Astrocytoma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (42, 'TCGA-S9-A6WH', 'Mixed glioma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (43, 'TCGA-WY-A85B', 'Astrocytoma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (44, 'TCGA-DH-5142', 'Astrocytoma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (45, 'TCGA-P5-A730', 'Mixed glioma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (46, 'TCGA-TM-A84C', 'Astrocytoma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (47, 'TCGA-TM-A84M', 'Oligodendroglioma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (48, 'TCGA-TM-A84O', 'Oligodendroglioma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (49, 'TCGA-S9-A7IZ', 'Astrocytoma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (50, 'TCGA-S9-A7IX', 'Astrocytoma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (51, 'TCGA-S9-A7QZ', 'Oligodendroglioma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (52, 'TCGA-DB-A75L', 'Astrocytoma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (53, 'TCGA-E1-A7YO', 'Oligodendroglioma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (54, 'TCGA-P5-A5EZ', 'Astrocytoma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (55, 'TCGA-DU-A76L', 'Oligodendroglioma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (56, 'TCGA-QH-A6X8', 'Oligodendroglioma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (57, 'TCGA-14-0817', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (58, 'TCGA-HW-8319', 'Astrocytoma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (59, 'TCGA-19-5958', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (60, 'TCGA-DB-A4XE', 'Mixed glioma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (61, 'TCGA-19-2625', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (62, 'TCGA-S9-A7R8', 'Astrocytoma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (63, 'TCGA-14-1825', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (64, 'TCGA-HT-7856', 'Oligodendroglioma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (65, 'TCGA-27-2521', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (66, 'TCGA-E1-A7YY', 'Oligodendroglioma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (67, 'TCGA-OX-A56R', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (68, 'TCGA-TQ-A7RU', 'Oligodendroglioma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (69, 'TCGA-HT-7604', 'Astrocytoma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (70, 'TCGA-HW-7486', 'Oligodendroglioma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (71, 'TCGA-16-0849', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (72, 'TCGA-E1-5304', 'Astrocytoma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (73, 'TCGA-DU-6399', 'Oligodendroglioma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (74, 'TCGA-DU-A7TA', 'Oligodendroglioma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (75, 'TCGA-S9-A89Z', 'Astrocytoma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (76, 'TCGA-HT-A5RA', 'Astrocytoma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (77, 'TCGA-E1-5307', 'Astrocytoma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (78, 'TCGA-DB-5280', 'Mixed glioma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (79, 'TCGA-DU-6405', 'Astrocytoma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (80, 'TCGA-FG-A711', 'Oligodendroglioma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (81, 'TCGA-S9-A7J1', 'Oligodendroglioma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (82, 'TCGA-TM-A84R', 'Oligodendroglioma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (83, 'TCGA-S9-A7J2', 'Oligodendroglioma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (84, 'TCGA-HW-7495', 'Oligodendroglioma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (85, 'TCGA-VM-A8C9', 'Astrocytoma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (86, 'TCGA-HT-7677', 'Oligodendroglioma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (87, 'TCGA-DH-A7UU', 'Astrocytoma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (88, 'TCGA-76-6657', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (89, 'TCGA-E1-A7Z6', 'Astrocytoma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (90, 'TCGA-FG-A710', 'Oligodendroglioma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (91, 'TCGA-06-0158', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (92, 'TCGA-P5-A5ET', 'Oligodendroglioma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (93, 'TCGA-P5-A5F0', 'Oligodendroglioma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (94, 'TCGA-HW-7490', 'Astrocytoma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (95, 'TCGA-DU-7019', 'Mixed glioma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (96, 'TCGA-HT-8564', 'Astrocytoma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (97, 'TCGA-HT-7879', 'Mixed glioma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (98, 'TCGA-28-2501', '--');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (99, 'TCGA-DB-A64L', 'Oligodendroglioma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (100, 'TCGA-76-6280', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (101, 'TCGA-28-1747', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (102, 'TCGA-06-2559', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (103, 'TCGA-DU-7300', 'Oligodendroglioma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (104, 'TCGA-DU-A5TY', 'Astrocytoma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (105, 'TCGA-VM-A8CH', 'Astrocytoma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (106, 'TCGA-R8-A6YH', '--');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (107, 'TCGA-S9-A6WE', 'Oligodendroglioma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (108, 'TCGA-HT-7681', 'Mixed glioma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (109, 'TCGA-HT-7469', 'Oligodendroglioma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (110, 'TCGA-TM-A84F', 'Astrocytoma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (111, 'TCGA-06-0878', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (112, 'TCGA-06-0166', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (113, 'TCGA-28-5208', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (114, 'TCGA-28-1749', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (115, 'TCGA-19-1387', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (116, 'TCGA-12-0615', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (117, 'TCGA-27-1830', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (118, 'TCGA-KT-A7W1', 'Astrocytoma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (119, 'TCGA-06-2561', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (120, 'TCGA-FG-5964', 'Oligodendroglioma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (121, 'TCGA-S9-A6TX', 'Oligodendroglioma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (122, 'TCGA-P5-A5F2', 'Astrocytoma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (123, 'TCGA-DU-5874', 'Oligodendroglioma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (124, 'TCGA-DU-A5TT', 'Oligodendroglioma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (125, 'TCGA-CS-5396', 'Oligodendroglioma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (126, 'TCGA-14-0786', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (127, 'TCGA-DU-7302', 'Oligodendroglioma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (128, 'TCGA-S9-A6TW', 'Oligodendroglioma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (129, 'TCGA-RY-A845', 'Mixed glioma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (130, 'TCGA-HT-A61A', 'Oligodendroglioma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (131, 'TCGA-DU-7018', 'Oligodendroglioma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (132, 'TCGA-HW-7489', 'Mixed glioma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (133, 'TCGA-R8-A6ML', 'Oligodendroglioma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (134, 'TCGA-DH-5144', 'Oligodendroglioma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (135, 'TCGA-DU-7013', 'Astrocytoma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (136, 'TCGA-CS-4941', 'Astrocytoma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (137, 'TCGA-WY-A85E', 'Mixed glioma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (138, 'TCGA-DH-A7UR', 'Oligodendroglioma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (139, 'TCGA-HT-7689', 'Oligodendroglioma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (140, 'TCGA-S9-A7R7', 'Astrocytoma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (141, 'TCGA-HT-A619', 'Oligodendroglioma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (142, 'TCGA-DU-7012', 'Astrocytoma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (143, 'TCGA-S9-A6UB', 'Oligodendroglioma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (144, 'TCGA-DB-5281', 'Mixed glioma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (145, 'TCGA-QH-A6CX', 'Astrocytoma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (146, 'TCGA-E1-5318', 'Oligodendroglioma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (147, 'TCGA-CS-6290', 'Astrocytoma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (148, 'TCGA-S9-A6U2', 'Oligodendroglioma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (149, 'TCGA-HT-A74J', 'Mixed glioma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (150, 'TCGA-WY-A859', 'Astrocytoma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (151, 'TCGA-HT-A5RB', 'Astrocytoma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (152, 'TCGA-DU-8168', 'Oligodendroglioma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (153, 'TCGA-QH-A6X3', 'Mixed glioma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (154, 'TCGA-DU-5853', 'Mixed glioma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (155, 'TCGA-CS-6667', 'Astrocytoma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (156, 'TCGA-S9-A89V', 'Astrocytoma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (157, 'TCGA-HT-8012', 'Oligodendroglioma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (158, 'TCGA-S9-A7IY', 'Mixed glioma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (159, 'TCGA-TQ-A7RS', 'Oligodendroglioma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (160, 'TCGA-QH-A6XC', 'Astrocytoma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (161, 'TCGA-CS-6668', 'Oligodendroglioma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (162, 'TCGA-DB-5277', 'Astrocytoma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (163, 'TCGA-CS-6186', 'Mixed glioma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (164, 'TCGA-HT-A4DS', 'Astrocytoma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (165, 'TCGA-DU-8165', 'Oligodendroglioma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (166, 'TCGA-HT-7605', 'Oligodendroglioma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (167, 'TCGA-DU-6410', 'Oligodendroglioma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (168, 'TCGA-RY-A83Z', 'Astrocytoma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (169, 'TCGA-HW-8321', 'Astrocytoma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (170, 'TCGA-S9-A7QW', 'Astrocytoma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (171, 'TCGA-S9-A6WL', 'Astrocytoma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (172, 'TCGA-DU-A5TW', 'Astrocytoma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (173, 'TCGA-HW-A5KL', 'Astrocytoma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (174, 'TCGA-WY-A85A', 'Astrocytoma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (175, 'TCGA-P5-A72Z', 'Oligodendroglioma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (176, 'TCGA-DU-8163', 'Mixed glioma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (177, 'TCGA-DB-5275', 'Mixed glioma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (178, 'TCGA-FG-8187', 'Mixed glioma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (179, 'TCGA-HT-7875', 'Oligodendroglioma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (180, 'TCGA-P5-A5EU', 'Astrocytoma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (181, 'TCGA-HT-7478', 'Astrocytoma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (182, 'TCGA-QH-A65S', 'Mixed glioma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (183, 'TCGA-HT-7881', 'Oligodendroglioma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (184, 'TCGA-DH-5140', 'Mixed glioma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (185, 'TCGA-WY-A85D', 'Mixed glioma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (186, 'TCGA-TQ-A7RK', 'Oligodendroglioma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (187, 'TCGA-TQ-A7RO', 'Mixed glioma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (188, 'TCGA-FG-8188', 'Mixed glioma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (189, 'TCGA-FG-6688', 'Astrocytoma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (190, 'TCGA-FG-8182', 'Oligodendroglioma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (191, 'TCGA-HT-A5R7', 'Astrocytoma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (192, 'TCGA-HT-7479', 'Astrocytoma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (193, 'TCGA-DB-5276', 'Mixed glioma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (194, 'TCGA-DU-8167', 'Mixed glioma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (195, 'TCGA-HT-8113', 'Oligodendroglioma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (196, 'TCGA-S9-A7R2', 'Astrocytoma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (197, 'TCGA-E1-A7YM', 'Astrocytoma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (198, 'TCGA-HT-7483', 'Mixed glioma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (199, 'TCGA-QH-A6CW', 'Mixed glioma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (200, 'TCGA-S9-A7IS', 'Astrocytoma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (201, 'TCGA-DU-8162', 'Mixed glioma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (202, 'TCGA-P5-A5EV', 'Astrocytoma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (203, 'TCGA-QH-A6X4', 'Mixed glioma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (204, 'TCGA-DU-A5TP', 'Astrocytoma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (205, 'TCGA-FG-6692', 'Oligodendroglioma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (206, 'TCGA-HT-A74H', 'Astrocytoma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (207, 'TCGA-DU-A6S2', 'Oligodendroglioma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (208, 'TCGA-DB-A64Q', 'Mixed glioma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (209, 'TCGA-DU-6394', 'Oligodendroglioma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (210, 'TCGA-DU-A5TR', 'Mixed glioma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (211, 'TCGA-R8-A6MO', 'Oligodendroglioma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (212, 'TCGA-S9-A7IQ', 'Mixed glioma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (213, 'TCGA-FG-8189', 'Oligodendroglioma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (214, 'TCGA-TM-A7CF', 'Astrocytoma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (215, 'TCGA-FG-A6IZ', 'Oligodendroglioma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (216, 'TCGA-HT-7687', 'Oligodendroglioma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (217, 'TCGA-TM-A84J', 'Oligodendroglioma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (218, 'TCGA-HT-A61C', 'Oligodendroglioma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (219, 'TCGA-DU-A76R', 'Oligodendroglioma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (220, 'TCGA-FG-A70Z', 'Mixed glioma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (221, 'TCGA-HT-7481', 'Oligodendroglioma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (222, 'TCGA-HT-7474', 'Mixed glioma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (223, 'TCGA-DB-A4XB', 'Astrocytoma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (224, 'TCGA-FG-A87N', 'Astrocytoma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (225, 'TCGA-S9-A7J0', 'Oligodendroglioma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (226, 'TCGA-CS-5397', 'Astrocytoma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (227, 'TCGA-WY-A85C', 'Astrocytoma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (228, 'TCGA-CS-6188', 'Astrocytoma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (229, 'TCGA-HT-7690', 'Mixed glioma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (230, 'TCGA-TQ-A7RN', 'Oligodendroglioma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (231, 'TCGA-FG-A6J1', 'Oligodendroglioma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (232, 'TCGA-TM-A7C5', 'Mixed glioma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (233, 'TCGA-DU-5854', 'Astrocytoma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (234, 'TCGA-TM-A84T', 'Mixed glioma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (235, 'TCGA-DH-A669', 'Oligodendroglioma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (236, 'TCGA-FG-A4MW', 'Mixed glioma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (237, 'TCGA-S9-A6TY', 'Oligodendroglioma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (238, 'TCGA-RY-A83Y', 'Oligodendroglioma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (239, 'TCGA-06-A5U1', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (240, 'TCGA-E1-A7YH', 'Astrocytoma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (241, 'TCGA-DH-5141', 'Oligodendroglioma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (242, 'TCGA-E1-5302', 'Astrocytoma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (243, 'TCGA-HT-A615', 'Oligodendroglioma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (244, 'TCGA-19-5951', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (245, 'TCGA-HT-7603', 'Oligodendroglioma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (246, 'TCGA-HT-7676', 'Oligodendroglioma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (247, 'TCGA-76-6191', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (248, 'TCGA-S9-A6WP', 'Mixed glioma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (249, 'TCGA-HT-7873', 'Mixed glioma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (250, 'TCGA-19-4065', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (251, 'TCGA-HT-A4DV', 'Oligodendroglioma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (252, 'TCGA-HT-7473', 'Mixed glioma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (253, 'TCGA-RR-A6KA', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (254, 'TCGA-DB-5270', 'Mixed glioma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (255, 'TCGA-06-0221', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (256, 'TCGA-DU-6400', 'Oligodendroglioma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (257, 'TCGA-28-2502', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (258, 'TCGA-HW-8322', 'Oligodendroglioma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (259, 'TCGA-HT-7480', 'Oligodendroglioma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (260, 'TCGA-06-5859', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (261, 'TCGA-06-6389', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (262, 'TCGA-E1-A7YW', 'Mixed glioma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (263, 'TCGA-32-2495', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (264, 'TCGA-06-0743', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (265, 'TCGA-12-0821', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (266, 'TCGA-DU-7009', 'Oligodendroglioma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (267, 'TCGA-HT-8108', 'Oligodendroglioma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (268, 'TCGA-DU-7306', 'Mixed glioma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (269, 'TCGA-DU-7006', 'Astrocytoma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (270, 'TCGA-DB-A64P', 'Oligodendroglioma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (271, 'TCGA-P5-A72W', 'Astrocytoma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (272, 'TCGA-28-1755', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (273, 'TCGA-HT-7688', 'Oligodendroglioma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (274, 'TCGA-VM-A8CD', 'Astrocytoma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (275, 'TCGA-32-4211', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (276, 'TCGA-06-2562', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (277, 'TCGA-32-4209', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (278, 'TCGA-41-3393', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (279, 'TCGA-76-4932', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (280, 'TCGA-12-0826', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (281, 'TCGA-27-2519', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (282, 'TCGA-RR-A6KB', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (283, 'TCGA-DB-A64X', 'Astrocytoma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (284, 'TCGA-27-1831', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (285, 'TCGA-S9-A7R1', 'Oligodendroglioma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (286, 'TCGA-HT-7877', 'Oligodendroglioma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (287, 'TCGA-28-2510', '--');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (288, 'TCGA-DH-A66F', 'Oligodendroglioma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (289, 'TCGA-HT-7684', 'Mixed glioma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (290, 'TCGA-06-0644', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (291, 'TCGA-P5-A77W', 'Mixed glioma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (292, 'TCGA-HT-A5R9', 'Oligodendroglioma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (293, 'TCGA-06-2569', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (294, 'TCGA-E1-A7YV', 'Mixed glioma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (295, 'TCGA-E1-A7YS', 'Oligodendroglioma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (296, 'TCGA-32-1977', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (297, 'TCGA-P5-A5F1', 'Astrocytoma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (298, 'TCGA-S9-A6WN', 'Astrocytoma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (299, 'TCGA-DU-A7T8', 'Mixed glioma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (300, 'TCGA-HW-7487', 'Oligodendroglioma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (301, 'TCGA-DU-A7TJ', 'Astrocytoma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (302, 'TCGA-TM-A7C3', 'Astrocytoma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (303, 'TCGA-DU-5855', 'Mixed glioma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (304, 'TCGA-DU-A6S7', 'Astrocytoma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (305, 'TCGA-06-0187', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (306, 'TCGA-S9-A6TV', 'Mixed glioma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (307, 'TCGA-TQ-A7RJ', 'Mixed glioma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (308, 'TCGA-26-5136', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (309, 'TCGA-DH-A66B', 'Astrocytoma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (310, 'TCGA-RY-A843', 'Astrocytoma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (311, 'TCGA-06-0882', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (312, 'TCGA-HT-8104', 'Astrocytoma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (313, 'TCGA-16-0850', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (314, 'TCGA-RY-A840', 'Oligodendroglioma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (315, 'TCGA-DU-6395', 'Mixed glioma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (316, 'TCGA-32-1976', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (317, 'TCGA-FG-A87Q', 'Astrocytoma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (318, 'TCGA-FG-8191', 'Oligodendroglioma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (319, 'TCGA-HT-7606', 'Astrocytoma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (320, 'TCGA-HT-7857', 'Astrocytoma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (321, 'TCGA-DU-7015', 'Oligodendroglioma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (322, 'TCGA-HT-7609', 'Mixed glioma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (323, 'TCGA-S9-A6WI', 'Mixed glioma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (324, 'TCGA-06-0877', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (325, 'TCGA-4W-AA9R', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (326, 'TCGA-06-2564', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (327, 'TCGA-19-1788', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (328, 'TCGA-P5-A733', 'Astrocytoma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (329, 'TCGA-12-0707', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (330, 'TCGA-E1-A7Z4', 'Astrocytoma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (331, 'TCGA-S9-A6TZ', 'Astrocytoma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (332, 'TCGA-06-0214', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (333, 'TCGA-EZ-7264', 'Oligodendroglioma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (334, 'TCGA-14-0781', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (335, 'TCGA-4W-AA9T', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (336, 'TCGA-FG-6691', 'Astrocytoma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (337, 'TCGA-DU-6401', 'Oligodendroglioma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (338, 'TCGA-DB-5278', 'Oligodendroglioma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (339, 'TCGA-HT-8109', 'Oligodendroglioma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (340, 'TCGA-FG-A4MT', 'Oligodendroglioma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (341, 'TCGA-S9-A7QY', 'Mixed glioma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (342, 'TCGA-DU-7292', 'Astrocytoma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (343, 'TCGA-DU-6396', 'Mixed glioma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (344, 'TCGA-CS-4943', 'Astrocytoma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (345, 'TCGA-W9-A837', 'Oligodendroglioma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (346, 'TCGA-VV-A829', 'Mixed glioma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (347, 'TCGA-FG-7641', 'Oligodendroglioma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (348, 'TCGA-FN-7833', 'Mixed glioma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (349, 'TCGA-HT-7471', 'Oligodendroglioma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (350, 'TCGA-06-5856', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (351, 'TCGA-HT-7695', 'Oligodendroglioma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (352, 'TCGA-HT-7470', 'Oligodendroglioma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (353, 'TCGA-41-6646', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (354, 'TCGA-DB-A4XC', 'Mixed glioma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (355, 'TCGA-CS-5390', 'Oligodendroglioma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (356, 'TCGA-06-0145', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (357, 'TCGA-HT-7855', 'Astrocytoma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (358, 'TCGA-26-1439', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (359, 'TCGA-12-1093', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (360, 'TCGA-14-0736', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (361, 'TCGA-06-0745', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (362, 'TCGA-14-0789', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (363, 'TCGA-26-6173', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (364, 'TCGA-27-1838', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (365, 'TCGA-DU-A6S6', 'Mixed glioma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (366, 'TCGA-VM-A8CB', 'Oligodendroglioma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (367, 'TCGA-QH-A6CU', 'Oligodendroglioma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (368, 'TCGA-HT-7485', 'Astrocytoma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (369, 'TCGA-TQ-A7RW', 'Mixed glioma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (370, 'TCGA-76-6663', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (371, 'TCGA-HT-7608', 'Mixed glioma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (372, 'TCGA-32-2494', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (373, 'TCGA-06-2567', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (374, 'TCGA-FG-A713', 'Mixed glioma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (375, 'TCGA-DH-A7US', 'Oligodendroglioma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (376, 'TCGA-R8-A73M', 'Oligodendroglioma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (377, 'TCGA-HT-A74O', 'Astrocytoma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (378, 'TCGA-HT-7468', 'Oligodendroglioma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (379, 'TCGA-HT-7880', 'Mixed glioma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (380, 'TCGA-HT-7858', 'Astrocytoma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (381, 'TCGA-HT-A614', 'Mixed glioma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (382, 'TCGA-HW-7491', 'Oligodendroglioma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (383, 'TCGA-41-2572', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (384, 'TCGA-FG-5963', 'Astrocytoma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (385, 'TCGA-12-0775', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (386, 'TCGA-WH-A86K', 'Astrocytoma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (387, 'TCGA-41-3392', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (388, 'TCGA-DU-6403', 'Mixed glioma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (389, 'TCGA-DU-5870', 'Oligodendroglioma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (390, 'TCGA-14-3477', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (391, 'TCGA-06-A6S1', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (392, 'TCGA-P5-A736', 'Astrocytoma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (393, 'TCGA-12-0692', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (394, 'TCGA-P5-A72X', 'Astrocytoma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (395, 'TCGA-14-1795', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (396, 'TCGA-HT-8011', 'Astrocytoma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (397, 'TCGA-19-1386', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (398, 'TCGA-CS-6670', 'Oligodendroglioma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (399, 'TCGA-19-A6J5', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (400, 'TCGA-HT-8114', 'Mixed glioma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (401, 'TCGA-06-6699', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (402, 'TCGA-FG-6690', 'Oligodendroglioma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (403, 'TCGA-16-0848', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (404, 'TCGA-74-6584', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (405, 'TCGA-12-0820', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (406, 'TCGA-DH-A7UV', 'Astrocytoma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (407, 'TCGA-DU-6408', 'Oligodendroglioma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (408, 'TCGA-TQ-A7RG', 'Mixed glioma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (409, 'TCGA-IK-7675', 'Oligodendroglioma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (410, 'TCGA-14-4157', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (411, 'TCGA-VM-A8CA', 'Oligodendroglioma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (412, 'TCGA-TM-A84I', 'Astrocytoma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (413, 'TCGA-06-0130', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (414, 'TCGA-HT-A61B', 'Astrocytoma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (415, 'TCGA-02-2485', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (416, 'TCGA-DB-A64U', 'Mixed glioma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (417, 'TCGA-E1-A7YU', 'Mixed glioma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (418, 'TCGA-DU-5847', 'Astrocytoma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (419, 'TCGA-E1-A7YJ', 'Astrocytoma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (420, 'TCGA-12-5299', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (421, 'TCGA-DB-A4XA', 'Mixed glioma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (422, 'TCGA-12-3646', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (423, 'TCGA-06-2558', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (424, 'TCGA-DU-5852', 'Mixed glioma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (425, 'TCGA-06-2565', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (426, 'TCGA-TM-A7CA', 'Astrocytoma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (427, 'TCGA-06-6391', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (428, 'TCGA-06-0238', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (429, 'TCGA-76-4926', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (430, 'TCGA-06-A7TL', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (431, 'TCGA-14-0790', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (432, 'TCGA-QH-A65X', 'Mixed glioma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (433, 'TCGA-12-0616', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (434, 'TCGA-VM-A8CE', 'Oligodendroglioma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (435, 'TCGA-DU-6407', 'Oligodendroglioma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (436, 'TCGA-TQ-A7RP', 'Mixed glioma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (437, 'TCGA-HW-A5KJ', 'Oligodendroglioma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (438, 'TCGA-E1-A7YL', 'Astrocytoma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (439, 'TCGA-TM-A84H', 'Mixed glioma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (440, 'TCGA-DU-8158', 'Astrocytoma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (441, 'TCGA-HT-7472', 'Oligodendroglioma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (442, 'TCGA-HT-7692', 'Mixed glioma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (443, 'TCGA-FG-7643', 'Mixed glioma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (444, 'TCGA-DB-5273', 'Astrocytoma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (445, 'TCGA-02-0047', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (446, 'TCGA-TQ-A7RV', 'Astrocytoma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (447, 'TCGA-VV-A86M', 'Astrocytoma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (448, 'TCGA-19-5955', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (449, 'TCGA-DU-A5TU', 'Astrocytoma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (450, 'TCGA-14-1827', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (451, 'TCGA-DU-A7TD', 'Mixed glioma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (452, 'TCGA-DB-A75K', 'Mixed glioma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (453, 'TCGA-06-0157', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (454, 'TCGA-S9-A7QX', 'Astrocytoma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (455, 'TCGA-E1-A7YI', 'Astrocytoma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (456, 'TCGA-06-0168', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (457, 'TCGA-TQ-A7RI', 'Oligodendroglioma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (458, 'TCGA-HT-7860', 'Astrocytoma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (459, 'TCGA-26-5135', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (460, 'TCGA-FG-8185', 'Astrocytoma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (461, 'TCGA-P5-A780', 'Astrocytoma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (462, 'TCGA-E1-A7YQ', 'Oligodendroglioma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (463, 'TCGA-06-6698', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (464, 'TCGA-S9-A6U5', 'Astrocytoma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (465, 'TCGA-26-5134', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (466, 'TCGA-HT-8107', 'Oligodendroglioma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (467, 'TCGA-CS-4942', 'Astrocytoma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (468, 'TCGA-S9-A6U9', 'Astrocytoma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (469, 'TCGA-HT-7686', 'Astrocytoma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (470, 'TCGA-DB-A75P', 'Astrocytoma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (471, 'TCGA-12-5295', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (472, 'TCGA-P5-A5EW', 'Astrocytoma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (473, 'TCGA-06-0154', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (474, 'TCGA-12-0691', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (475, 'TCGA-12-1602', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (476, 'TCGA-12-0670', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (477, 'TCGA-HT-7607', 'Astrocytoma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (478, 'TCGA-DU-7309', 'Oligodendroglioma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (479, 'TCGA-28-1757', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (480, 'TCGA-P5-A737', 'Mixed glioma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (481, 'TCGA-12-0829', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (482, 'TCGA-S9-A6WM', 'Astrocytoma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (483, 'TCGA-06-0749', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (484, 'TCGA-FG-7636', 'Astrocytoma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (485, 'TCGA-06-5413', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (486, 'TCGA-E1-5322', 'Mixed glioma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (487, 'TCGA-06-0646', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (488, 'TCGA-TQ-A7RF', 'Oligodendroglioma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (489, 'TCGA-26-6174', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (490, 'TCGA-DU-7010', 'Astrocytoma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (491, 'TCGA-12-0662', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (492, 'TCGA-QH-A6CS', 'Astrocytoma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (493, 'TCGA-28-2514', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (494, 'TCGA-HT-7476', 'Astrocytoma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (495, 'TCGA-06-0650', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (496, 'TCGA-HT-7884', 'Astrocytoma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (497, 'TCGA-76-4931', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (498, 'TCGA-HT-8111', 'Mixed glioma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (499, 'TCGA-DU-A7TC', 'Astrocytoma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (500, 'TCGA-TQ-A7RR', 'Mixed glioma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (501, 'TCGA-TQ-A8XE', 'Oligodendroglioma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (502, 'TCGA-HT-A617', 'Oligodendroglioma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (503, 'TCGA-DB-A64V', 'Oligodendroglioma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (504, 'TCGA-DU-8166', 'Mixed glioma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (505, 'TCGA-TM-A7C4', 'Astrocytoma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (506, 'TCGA-06-0649', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (507, 'TCGA-FG-7634', 'Oligodendroglioma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (508, 'TCGA-06-0241', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (509, 'TCGA-QH-A6XA', 'Mixed glioma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (510, 'TCGA-CS-6666', 'Astrocytoma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (511, 'TCGA-19-5956', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (512, 'TCGA-HT-7602', 'Oligodendroglioma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (513, 'TCGA-HT-7610', 'Mixed glioma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (514, 'TCGA-S9-A6TU', 'Astrocytoma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (515, 'TCGA-FG-A60K', 'Mixed glioma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (516, 'TCGA-DH-A66G', 'Oligodendroglioma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (517, 'TCGA-S9-A6U8', 'Astrocytoma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (518, 'TCGA-TQ-A7RQ', 'Oligodendroglioma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (519, 'TCGA-HT-8563', 'Astrocytoma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (520, 'TCGA-TQ-A7RH', 'Mixed glioma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (521, 'TCGA-06-0173', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (522, 'TCGA-HT-A74L', 'Mixed glioma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (523, 'TCGA-HT-7475', 'Mixed glioma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (524, 'TCGA-S9-A6U1', 'Astrocytoma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (525, 'TCGA-QH-A6X9', 'Oligodendroglioma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (526, 'TCGA-DU-7301', 'Oligodendroglioma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (527, 'TCGA-02-2466', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (528, 'TCGA-IK-8125', 'Mixed glioma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (529, 'TCGA-06-6697', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (530, 'TCGA-FG-6689', 'Astrocytoma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (531, 'TCGA-06-0129', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (532, 'TCGA-S9-A6WQ', 'Mixed glioma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (533, 'TCGA-HT-8013', 'Mixed glioma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (534, 'TCGA-06-6695', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (535, 'TCGA-HT-A616', 'Astrocytoma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (536, 'TCGA-15-1446', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (537, 'TCGA-DU-7008', 'Oligodendroglioma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (538, 'TCGA-16-1048', '--');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (539, 'TCGA-E1-A7YD', 'Astrocytoma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (540, 'TCGA-27-2526', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (541, 'TCGA-76-6192', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (542, 'TCGA-27-2523', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (543, 'TCGA-06-0119', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (544, 'TCGA-DH-5143', 'Mixed glioma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (545, 'TCGA-E1-A7YK', 'Astrocytoma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (546, 'TCGA-27-1835', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (547, 'TCGA-DB-A64R', 'Oligodendroglioma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (548, 'TCGA-4W-AA9S', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (549, 'TCGA-TM-A84Q', 'Astrocytoma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (550, 'TCGA-DB-A64S', 'Mixed glioma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (551, 'TCGA-WY-A858', 'Astrocytoma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (552, 'TCGA-P5-A5EX', 'Oligodendroglioma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (553, 'TCGA-F6-A8O4', 'Astrocytoma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (554, 'TCGA-DU-7294', 'Oligodendroglioma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (555, 'TCGA-R8-A6MK', 'Oligodendroglioma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (556, 'TCGA-E1-5305', 'Astrocytoma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (557, 'TCGA-VM-A8CF', 'Astrocytoma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (558, 'TCGA-CS-6665', 'Astrocytoma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (559, 'TCGA-FG-5965', 'Mixed glioma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (560, 'TCGA-19-2629', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (561, 'TCGA-HT-7601', 'Astrocytoma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (562, 'TCGA-HT-7854', 'Astrocytoma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (563, 'TCGA-RR-A6KC', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (564, 'TCGA-06-0237', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (565, 'TCGA-06-0211', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (566, 'TCGA-76-6283', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (567, 'TCGA-06-0188', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (568, 'TCGA-32-4208', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (569, 'TCGA-RY-A847', 'Oligodendroglioma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (570, 'TCGA-DU-5849', 'Oligodendroglioma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (571, 'TCGA-FG-7637', 'Mixed glioma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (572, 'TCGA-QH-A65R', 'Oligodendroglioma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (573, 'TCGA-06-5414', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (574, 'TCGA-12-3644', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (575, 'TCGA-87-5896', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (576, 'TCGA-06-5410', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (577, 'TCGA-14-1821', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (578, 'TCGA-HT-8110', 'Astrocytoma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (579, 'TCGA-06-0126', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (580, 'TCGA-TM-A84L', 'Mixed glioma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (581, 'TCGA-14-1450', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (582, 'TCGA-12-0819', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (583, 'TCGA-32-1991', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (584, 'TCGA-76-6660', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (585, 'TCGA-76-6285', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (586, 'TCGA-74-6575', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (587, 'TCGA-81-5911', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (588, 'TCGA-28-5220', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (589, 'TCGA-12-0827', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (590, 'TCGA-06-0210', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (591, 'TCGA-06-0213', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (592, 'TCGA-14-1037', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (593, 'TCGA-06-0645', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (594, 'TCGA-06-0171', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (595, 'TCGA-19-5954', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (596, 'TCGA-27-1836', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (597, 'TCGA-06-0876', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (598, 'TCGA-19-2621', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (599, 'TCGA-14-0787', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (600, 'TCGA-02-2483', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (601, 'TCGA-06-0939', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (602, 'TCGA-32-1986', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (603, 'TCGA-12-1599', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (604, 'TCGA-06-0152', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (605, 'TCGA-32-1982', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (606, 'TCGA-32-2634', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (607, 'TCGA-06-A6S0', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (608, 'TCGA-76-4927', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (609, 'TCGA-19-5950', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (610, 'TCGA-06-1804', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (611, 'TCGA-19-2631', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (612, 'TCGA-12-3649', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (613, 'TCGA-14-1829', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (614, 'TCGA-27-1833', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (615, 'TCGA-76-6282', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (616, 'TCGA-06-6388', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (617, 'TCGA-32-1979', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (618, 'TCGA-14-0865', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (619, 'TCGA-S9-A7R3', 'Astrocytoma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (620, 'TCGA-16-1045', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (621, 'TCGA-28-5209', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (622, 'TCGA-19-A6J4', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (623, 'TCGA-19-5947', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (624, 'TCGA-06-0155', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (625, 'TCGA-76-6664', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (626, 'TCGA-32-5222', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (627, 'TCGA-P5-A735', 'Astrocytoma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (628, 'TCGA-06-0124', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (629, 'TCGA-02-0033', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (630, 'TCGA-HT-A618', 'Astrocytoma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (631, 'TCGA-06-0151', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (632, 'TCGA-26-5139', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (633, 'TCGA-E1-A7Z2', 'Oligodendroglioma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (634, 'TCGA-76-4934', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (635, 'TCGA-TQ-A7RM', 'Mixed glioma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (636, 'TCGA-06-0141', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (637, 'TCGA-HT-7694', 'Oligodendroglioma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (638, 'TCGA-06-0881', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (639, 'TCGA-VM-A8C8', 'Oligodendroglioma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (640, 'TCGA-HT-7616', 'Oligodendroglioma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (641, 'TCGA-CS-5395', 'Mixed glioma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (642, 'TCGA-14-1034', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (643, 'TCGA-S9-A7J3', 'Oligodendroglioma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (644, 'TCGA-12-0818', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (645, 'TCGA-E1-5303', 'Astrocytoma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (646, 'TCGA-27-1837', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (647, 'TCGA-CS-4944', 'Astrocytoma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (648, 'TCGA-12-0618', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (649, 'TCGA-HT-7882', 'Oligodendroglioma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (650, 'TCGA-28-2513', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (651, 'TCGA-DH-A7UT', 'Astrocytoma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (652, 'TCGA-06-5408', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (653, 'TCGA-76-6662', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (654, 'TCGA-12-3648', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (655, 'TCGA-81-5910', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (656, 'TCGA-15-0742', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (657, 'TCGA-06-5415', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (658, 'TCGA-DB-A64O', 'Mixed glioma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (659, 'TCGA-VW-A7QS', 'Oligodendroglioma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (660, 'TCGA-QH-A870', 'Mixed glioma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (661, 'TCGA-12-1088', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (662, 'TCGA-DU-A5TS', 'Oligodendroglioma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (663, 'TCGA-19-A60I', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (664, 'TCGA-12-1092', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (665, 'TCGA-P5-A731', 'Mixed glioma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (666, 'TCGA-19-1790', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (667, 'TCGA-KT-A74X', 'Mixed glioma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (668, 'TCGA-14-0812', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (669, 'TCGA-FG-A4MU', 'Mixed glioma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (670, 'TCGA-16-1460', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (671, 'TCGA-E1-5311', 'Oligodendroglioma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (672, 'TCGA-HT-7902', 'Mixed glioma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (673, 'TCGA-DU-7290', 'Astrocytoma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (674, 'TCGA-DB-5274', 'Mixed glioma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (675, 'TCGA-FG-A60L', 'Astrocytoma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (676, 'TCGA-P5-A781', 'Astrocytoma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (677, 'TCGA-28-5204', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (678, 'TCGA-41-3915', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (679, 'TCGA-DB-A4XD', 'Astrocytoma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (680, 'TCGA-DU-6393', 'Oligodendroglioma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (681, 'TCGA-S9-A6U0', 'Astrocytoma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (682, 'TCGA-DU-7298', 'Astrocytoma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (683, 'TCGA-DU-7299', 'Astrocytoma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (684, 'TCGA-DU-A7TG', 'Oligodendroglioma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (685, 'TCGA-FG-A6J3', 'Astrocytoma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (686, 'TCGA-DB-5279', 'Oligodendroglioma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (687, 'TCGA-14-1451', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (688, 'TCGA-06-1084', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (689, 'TCGA-12-3653', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (690, 'TCGA-06-0125', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (691, 'TCGA-28-1751', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (692, 'TCGA-QH-A6X5', 'Mixed glioma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (693, 'TCGA-76-6656', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (694, 'TCGA-06-0648', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (695, 'TCGA-CS-4938', 'Astrocytoma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (696, 'TCGA-DU-5872', 'Mixed glioma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (697, 'TCGA-14-2554', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (698, 'TCGA-06-0174', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (699, 'TCGA-DU-7007', 'Astrocytoma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (700, 'TCGA-19-1389', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (701, 'TCGA-P5-A77X', 'Mixed glioma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (702, 'TCGA-06-A7TK', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (703, 'TCGA-41-2571', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (704, 'TCGA-DU-7304', 'Mixed glioma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (705, 'TCGA-28-1753', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (706, 'TCGA-DU-A6S3', 'Oligodendroglioma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (707, 'TCGA-76-6193', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (708, 'TCGA-12-3650', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (709, 'TCGA-QH-A86X', 'Oligodendroglioma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (710, 'TCGA-E1-5319', 'Oligodendroglioma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (711, 'TCGA-14-1395', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (712, 'TCGA-HT-A5RC', 'Astrocytoma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (713, 'TCGA-32-2616', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (714, 'TCGA-HT-8106', 'Astrocytoma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (715, 'TCGA-06-5411', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (716, 'TCGA-S9-A6UA', 'Astrocytoma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (717, 'TCGA-28-5215', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (718, 'TCGA-19-5953', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (719, 'TCGA-TM-A84S', 'Oligodendroglioma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (720, 'TCGA-HT-7620', 'Oligodendroglioma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (721, 'TCGA-DU-A7T6', 'Oligodendroglioma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (722, 'TCGA-HT-7611', 'Mixed glioma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (723, 'TCGA-DU-A6S8', 'Oligodendroglioma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (724, 'TCGA-14-1043', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (725, 'TCGA-QH-A65V', 'Oligodendroglioma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (726, 'TCGA-76-6661', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (727, 'TCGA-06-0128', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (728, 'TCGA-28-6450', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (729, 'TCGA-28-2509', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (730, 'TCGA-12-1089', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (731, 'TCGA-14-0862', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (732, 'TCGA-27-1834', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (733, 'TCGA-32-2632', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (734, 'TCGA-19-5959', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (735, 'TCGA-TM-A84B', 'Astrocytoma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (736, 'TCGA-16-0846', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (737, 'TCGA-19-2624', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (738, 'TCGA-QH-A6CZ', 'Mixed glioma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (739, 'TCGA-TM-A84G', 'Oligodendroglioma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (740, 'TCGA-28-1746', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (741, 'TCGA-06-0686', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (742, 'TCGA-DU-8161', 'Mixed glioma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (743, 'TCGA-32-2491', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (744, 'TCGA-06-2557', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (745, 'TCGA-06-0750', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (746, 'TCGA-14-3476', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (747, 'TCGA-06-0209', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (748, 'TCGA-06-0132', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (749, 'TCGA-HT-7477', 'Astrocytoma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (750, 'TCGA-DU-6392', 'Astrocytoma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (751, 'TCGA-CS-5393', 'Astrocytoma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (752, 'TCGA-S9-A6WO', 'Astrocytoma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (753, 'TCGA-S9-A7R4', 'Astrocytoma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (754, 'TCGA-RY-A83X', 'Oligodendroglioma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (755, 'TCGA-HT-7693', 'Oligodendroglioma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (756, 'TCGA-HT-7467', 'Oligodendroglioma, NOS');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (757, 'TCGA-FG-8186', 'Mixed glioma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (758, 'TCGA-HW-A5KK', 'Astrocytoma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (759, 'TCGA-DB-A75O', 'Astrocytoma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (760, 'TCGA-DB-A64W', 'Mixed glioma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (761, 'TCGA-DB-A4XF', 'Astrocytoma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (762, 'TCGA-FG-7638', 'Oligodendroglioma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (763, 'TCGA-HT-A74K', 'Oligodendroglioma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (764, 'TCGA-HT-8105', 'Oligodendroglioma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (765, 'TCGA-S9-A6U6', 'Astrocytoma, anaplastic');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (766, 'TCGA-12-0656', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (767, 'TCGA-26-1799', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (768, 'TCGA-14-0871', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (769, 'TCGA-12-0657', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (770, 'TCGA-19-1786', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (771, 'TCGA-06-6390', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (772, 'TCGA-28-5219', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (773, 'TCGA-14-1455', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (774, 'TCGA-41-2575', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (775, 'TCGA-28-5216', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (776, 'TCGA-26-A7UX', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (777, 'TCGA-06-A5U0', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (778, 'TCGA-32-1980', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (779, 'TCGA-19-4068', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (780, 'TCGA-06-0744', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (781, 'TCGA-76-4935', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (782, 'TCGA-26-5133', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (783, 'TCGA-41-5651', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (784, 'TCGA-19-1787', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (785, 'TCGA-28-1745', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (786, 'TCGA-28-5213', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (787, 'TCGA-74-6577', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (788, 'TCGA-32-2638', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (789, 'TCGA-19-1791', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (790, 'TCGA-06-6693', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (791, 'TCGA-06-1087', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (792, 'TCGA-76-4928', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (793, 'TCGA-32-4210', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (794, 'TCGA-06-5412', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (795, 'TCGA-06-5417', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (796, 'TCGA-28-1752', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (797, 'TCGA-06-0747', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (798, 'TCGA-06-0169', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (799, 'TCGA-26-1442', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (800, 'TCGA-28-2499', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (801, 'TCGA-27-2518', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (802, 'TCGA-06-0216', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (803, 'TCGA-28-1750', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (804, 'TCGA-06-0137', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (805, 'TCGA-06-0184', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (806, 'TCGA-19-2620', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (807, 'TCGA-41-2573', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (808, 'TCGA-27-2524', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (809, 'TCGA-06-0190', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (810, 'TCGA-12-0773', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (811, 'TCGA-06-2563', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (812, 'TCGA-74-6573', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (813, 'TCGA-06-0185', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (814, 'TCGA-06-0140', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (815, 'TCGA-27-2528', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (816, 'TCGA-41-4097', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (817, 'TCGA-14-1823', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (818, 'TCGA-12-0619', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (819, 'TCGA-06-0219', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (820, 'TCGA-14-1456', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (821, 'TCGA-06-0192', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (822, 'TCGA-02-2486', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (823, 'TCGA-16-0861', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (824, 'TCGA-06-0875', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (825, 'TCGA-06-0879', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (826, 'TCGA-74-6581', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (827, 'TCGA-74-6578', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (828, 'TCGA-14-1396', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (829, 'TCGA-06-0195', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (830, 'TCGA-28-5218', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (831, 'TCGA-06-5416', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (832, 'TCGA-19-2623', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (833, 'TCGA-02-0003', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (834, 'TCGA-06-0189', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (835, 'TCGA-76-6286', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (836, 'TCGA-12-1597', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (837, 'TCGA-14-1453', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (838, 'TCGA-19-5960', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (839, 'TCGA-76-4929', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (840, 'TCGA-76-4925', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (841, 'TCGA-12-1600', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (842, 'TCGA-19-1789', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (843, 'TCGA-12-5301', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (844, 'TCGA-12-1598', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (845, 'TCGA-02-2470', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (846, 'TCGA-19-1385', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (847, 'TCGA-06-5858', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (848, 'TCGA-06-1806', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (849, 'TCGA-12-0688', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (850, 'TCGA-12-3652', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (851, 'TCGA-14-0813', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (852, 'TCGA-32-1970', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (853, 'TCGA-06-2570', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (854, 'TCGA-27-2527', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (855, 'TCGA-14-0740', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (856, 'TCGA-02-0055', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (857, 'TCGA-06-5418', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (858, 'TCGA-06-6701', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (859, 'TCGA-19-1390', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (860, 'TCGA-06-1800', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (861, 'TCGA-32-4213', 'Glioblastoma');
INSERT INTO existing_table (info_id, case_id, primary_diagnosis) VALUES (862, 'TCGA-06-6694', 'Glioblastoma');
